- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart hostapd
  ansible.builtin.systemd:
    name: hostapd
    state: restarted
    force: true

- name: Apply iptables rules
  ansible.builtin.shell:
    cmd: iptables-restore < /etc/iptables/rules.template
  changed_when: true

- name: Save iptables rules
  ansible.builtin.shell:
    cmd: sudo netfilter-persistent save
  changed_when: true

- name: Restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted

- name: Apply netplan
  ansible.builtin.command: netplan apply
  changed_when: true
