- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart hostapd
  ansible.builtin.systemd:
    name: hostapd
    state: restarted

- name: Apply iptables rules
  ansible.builtin.command: iptables-restore < /etc/iptables/rules.v4
  changed_when: true

- name: Restart DHCP
  ansible.builtin.systemd:
    state: restarted

- name: Apply netplan
  ansible.builtin.command: netplan apply
  changed_when: true
