- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable AWG service
  ansible.builtin.systemd:
    name: awg-quick@{{ peer_interface.iface.name }}
    enabled: true
    state: started

- name: Restart AWG service
  ansible.builtin.systemd:
    name: awg-quick@{{ peer_interface.iface.name }}
    state: restarted

- name: Reboot host
  ansible.builtin.reboot:
    reboot_timeout: 3600
